name: Foundational Boogie CI

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Download and install Isabelle
        run: |
          wget --quiet https://isabelle.in.tum.de/dist/Isabelle2022_linux.tar.gz
          tar -xf Isabelle2022_linux.tar.gz
          rm Isabelle2022_linux.tar.gz
          mv Isabelle2022 isabelle_dir
          isabelle_dir/bin/isabelle version
          echo isabelle_dir/bin >> $GITHUB_PATH

      - name: Run Isabelle on Repo
        run: |
          isabelle build -j4 -c -D BoogieLang